### PR TITLE
Update EnvironmentConfigManager.cs

### PR DESCRIPTION
**Pull request by tspence**
Replace unnecessary log message.  On our server, this produces hundreds of log messages per second which reduces the signal-to-noise on our logging system.

### CODE REVIEW

**Comment by chris-hoefgen** [comment]
@tspence I think you are right that `logger.LogInformation` is not the right option, but we would like to keep some kind of messaging, even though it seems like a no-op. In our other SDKs this is more of a debug message, so you could change it to `logger.LogDebug` which should have a similar effect of reducing the messages in production.

In addition, PRs to our repos require titles that follow [Conventional Commit ](https://www.conventionalcommits.org/en/v1.0.0/#summary) standards, so you will need to update the title to something like: 

`fix: Config updates with 304 Modified response logged at debug level`

**Comment by tspence** [comment]
> @tspence I think you are right that `logger.LogInformation` is not the right option, but we would like to keep some kind of messaging, even though it seems like a no-op. In our other SDKs this is more of a debug message, so you could change it to `logger.LogDebug` which should have a similar effect of reducing the messages in production.
> 
> In addition, PRs to our repos require titles that follow [Conventional Commit ](https://www.conventionalcommits.org/en/v1.0.0/#summary) standards, so you will need to update the title to something like:
> 
> `chore: Config updates with 304 Modified response logged at debug level`

Thanks for the quick reply!  Let me consider your comments and re-imagine the pull request, if you're still amenable to me submitting a proposed change.

The concern we have is that, after adding DevCycle to our project, we started getting lots of unnecessary log messages that didn't identify themselves as being from DevCycle, so we had to dedicate effort to figure them out.  The content seemed worrying but ultimately turned out to be harmless.

What about a PR to make logging optional?  e.g. when setting up the library, you could make a call to disable logging, or limit logging to a specific level (warnings and up)?

Regardless, it might be useful to modify the usage of the logger to tag all logs as being DevCycle related.

Would you have any objections to those changes?

**Comment by chris-hoefgen** [comment]
By default our SDK logs to stdout and can be verbose to assist with initial setup and debugging of the SDK. You can customize the logging behaviour by providing your own LoggerFactory to the SDK during initialization, and use that to disable or reduce the amount of logging it generates.  Many of our users will set the minimum level to Error when deploying to production.

```
var loggerFactory = LoggerFactory.Create(builder =>
{
    builder
        .AddConsole() // Configure the logger to output to the console
        .SetMinimumLevel(LogLevel.Information); // Set the minimum log level to Information
});

DevCycleLocalClient api = new DevCycleLocalClientBuilder()
    .SetOptions(options ?? new DevCycleLocalOptions())
    .SetSDKKey("YOUR_DEVCYCLE_SDK_KEY")
    .SetLogger(loggerFactory)
    .Build();
```

**Comment by chris-hoefgen** [comment]
>> Regardless, it might be useful to modify the usage of the logger to tag all logs as being DevCycle related.

that is a good point, we will take a look at doing that to make sure the SDK does format log messages with some kind of DevCycle prefix.

**Comment by JamieSinn** [comment]
#112 addresses this!

Thank you for the PR/notice!

**Pull request closed without merging**
